file-version: 2
placeholders:
  npc: '&e[NPC] &c%npc_name%&f:'
  user: '&e[YOU] &b%player_name%&f:'
npc:
  '9999': choice-sample
use-actionbar: false
choice:
  text-model: '&c{I}&7)&e {S}'
  number-heads:
    '1': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZTZhYmI5Y2Y0MjUzMTBlOWRkZjFiNGE4OWExZjQ1ZjMwZGQzY2RiYzAyYzljMzdkN2Y2YzhmMWQ2NjA2ZCJ9fX0="
    '2': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvM2YyOWViYTZjY2YyOTc3Y2E5N2U0OWI1YjE1Mjc2OGM1NTA4Zjc0M2Q5OTQwZTgzM2JiZjA1YzkwMTFkYzg2In19fQ=="
    '3': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYjQ3N2QzY2UzMTczZTgzOWNmZjhjZTZlNzIwNTZlNDE3MTg1MzQ1NzczNmMzMTEyOGJlYTc5ZGU4NDk4MTY3In19fQ=="
    '4': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2ZhZDJkOGRmYTQ0YTRjNDVhMmQ2M2ViZDc1MzM4ZjJjZjZjNTI4OTUxZTE1ZjdhZGZiM2UzODE1ZDk3ZmU5In19fQ=="
    '5': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWQxZmVkNmEzZTIzYzYxZTZhMzZmYzdjOTJhMzU5MWNmODY3ZDk4OWUzYTA3ZjIxNTNmMGNkZjUwMmVjZiJ9fX0="
    '6': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWU3NjU1YTc2NWU0NmQ1YzI0OTI2OTQ2M2ZmZjg2ZDhlMGY2OGRlZDM1MzgzNzc2OWMyNjQ1YTdlZDA4ZiJ9fX0="
    '7': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDZjNjI0MzNiNzUxMTE0OTNlZjUzMmJkOTBhMjVhMWNmYTQ3ZGJkZTg1NDQyMDRkODU1ZjQxZjBmZTNlZTYifX19"
    '8': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWM2ODk3NWRhMmE2ZTZlYWEzZGI0NDc3YzM0YjdkNWU2OGExNWQyYzE5NGEwN2FlOTQwNjA4NjNhOTY3OGM2In19fQ=="
    '9': "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOWQyYjgyNGFlOGEwNTI5M2QyNDgzZmVmMjJiYTZmYjFkMzUyMTlkMTI1MjU2MGY0YWRkMWRhNzc0ODkyNyJ9fX0="