file-version: 1.0.1
placeholders:
  npc: '&e[NPC] &c%npc_name%&f:'
  user: '&e[YOU] &b%player_name%&f:'
npc:
  '9999': choice-sample
use-actionbar: false
updatexample: "HOLA"
choice:
  text-model: '&c{I}&7)&e {S}'
