main: me.iatog.characterdialogue.CharacterDialoguePlugin
version: 0.9
name: CharacterDialogue
author: iAtog
depend: [ Citizens ]
softdepend: [ PlaceHolderAPI, HolographicDisplays, DecentHolograms, floodgate, ConditionalEvents ]
api-version: 1.20

commands: