main: me.iatog.characterdialogue.CharacterDialoguePlugin
version: 0.9
name: CharacterDialogue
author: iAtog
depend: [ Citizens ]
softdepend: [ PlaceHolderAPI, HolographicDisplays, DecentHolograms, floodgate ]
api-version: 1.16

commands: